---
load_balancers:
  hosts:
    lb:
      ansible_host: 192.168.51.20

backend_servers:
  hosts:
    web1:
      ansible_host: 192.168.51.11
    web2:
      ansible_host: 192.168.51.19

database_servers:
  hosts:
    db:
      ansible_host: 192.168.51.18

[all:vars]
GUID=1790
